On branch wls-aks-auscaling Ran into problem just before Enable KEDA. modified:   articles/java/migration/migrate-weblogic-to-aks-with-keda-scaler-based-on-prometheus-metrics.md
Hello @galiacheng,

I am pushing several commits to this PR. It turns out this article needs some more work, but no worries! It's in great shape and just needs a little more.

I observe that when I try to create the configmap, I see it's already created:

```bash
kubectl create configmap ama-metrics-prometheus-config --from-file=prometheus-config -n kube-system
error: failed to create configmap: configmaps "ama-metrics-prometheus-config" already exists
```

Signed-off-by: Ed Burns <edburns@microsoft.com>